layout_spectrum: 0.9957447
color:
  saturation: 0.6702127
  brandStrength: 0.5235177
  lightness: 0.2765957
  rhythmicContrast: 0.6914893
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
typography_spectrum: 0.9042553
name: Bristol
